guiziweb_sylius_token_admin_token_product_index:
    path: /token-packs
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _sylius:
            section: admin
            template: "@GuiziwebSyliusTokenPlugin/admin/token_product/index.html.twig"
            grid: guiziweb_sylius_token_admin_token_product

guiziweb_sylius_token_admin_tariff:
    resource: |
        alias: guiziweb_sylius_token.tariff
        section: admin
        templates: "@SyliusAdmin/shared/crud"
        grid: guiziweb_sylius_token_admin_tariff
        vars:
            all:
                subheader: guiziweb_sylius_token.ui.tariffs_subheader
            index:
                icon: 'tabler:receipt'
    type: sylius.resource
    prefix: /

guiziweb_sylius_token_admin_wallet_index:
    path: /token-wallets
    methods: [GET]
    defaults:
        _controller: guiziweb_sylius_token.controller.wallet::indexAction
        _sylius:
            section: admin
            template: "@GuiziwebSyliusTokenPlugin/admin/wallet/index.html.twig"
            grid: guiziweb_sylius_token_admin_wallet

guiziweb_sylius_token_admin_wallet_adjust:
    path: /token-wallets/{id}/adjust
    methods: [GET, POST]
    defaults:
        _controller: Guiziweb\SyliusTokenPlugin\Controller\Admin\WalletAdjustmentController

guiziweb_sylius_token_admin_wallet_history:
    path: /token-wallets/{id}/history
    methods: [GET]
    defaults:
        _controller: guiziweb_sylius_token.controller.transaction::indexAction
        _sylius:
            section: admin
            template: "@GuiziwebSyliusTokenPlugin/admin/wallet/history.html.twig"
            grid: guiziweb_sylius_token_admin_wallet_history
