guiziweb_sylius_token_shop_account_tokens_index:
    path: /account/tokens
    methods: [GET]
    defaults:
        _controller: guiziweb_sylius_token.controller.transaction::indexAction
        _sylius:
            section: shop_account
            template: "@GuiziwebSyliusTokenPlugin/shop/account/tokens/index.html.twig"
            grid: guiziweb_sylius_token_shop_account_transaction
