sylius_grid:
    grids:
        guiziweb_sylius_token_admin_wallet_history:
            driver:
                name: doctrine/orm
                options:
                    class: "%guiziweb_sylius_token.model.transaction.class%"
                    repository:
                        method: createByWalletQueryBuilder
                        arguments:
                            - "expr:service('guiziweb_sylius_token.provider.current_wallet').getWallet()"
            sorting:
                createdAt: desc
            limits: [25, 50, 100]
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: ~
                    options:
                        format: Y-m-d H:i
                type:
                    type: twig
                    label: guiziweb_sylius_token.ui.transaction.type
                    sortable: ~
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/shared/grid/field/token_type.html.twig"
                amount:
                    type: twig
                    label: guiziweb_sylius_token.ui.transaction.amount
                    sortable: ~
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/shared/grid/field/token_amount.html.twig"
                reason:
                    type: twig
                    label: guiziweb_sylius_token.form.adjustment.reason
                    path: .
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/admin/wallet/grid/field/context.html.twig"
            filters:
                type:
                    type: select
                    label: guiziweb_sylius_token.ui.transaction.type
                    form_options:
                        choices:
                            guiziweb_sylius_token.ui.transaction.types.credit: credit
                            guiziweb_sylius_token.ui.transaction.types.debit: debit
                            guiziweb_sylius_token.ui.transaction.types.expiration: expiration
                reason:
                    type: string
                    label: guiziweb_sylius_token.form.adjustment.reason
