sylius_grid:
    grids:
        guiziweb_sylius_token_admin_wallet:
            driver:
                name: doctrine/orm
                options:
                    class: "%guiziweb_sylius_token.model.wallet.class%"
            sorting:
                createdAt: desc
            limits: [10, 25, 50]
            fields:
                customer:
                    type: twig
                    label: sylius.ui.customer
                    path: .
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/admin/wallet/grid/field/customer.html.twig"
                balance:
                    type: string
                    label: guiziweb_sylius_token.ui.balance
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: Y-m-d H:i
            filters:
                customer:
                    type: string
                    label: sylius.ui.customer
                    options:
                        fields: [customer.email, customer.firstName, customer.lastName]
            actions:
                item:
                    adjust:
                        type: default
                        label: guiziweb_sylius_token.ui.adjust
                        options:
                            link:
                                route: guiziweb_sylius_token_admin_wallet_adjust
                                parameters:
                                    id: resource.id
                                icon: 'tabler:coins'
