sylius_grid:
    grids:
        sylius_admin_product_variant:
            fields:
                tokenAmount:
                    type: string
                    label: guiziweb_sylius_token.ui.product_variant.token_amount
                    path: tokenAmount
                    sortable: tokenAmount
                    position: 200
                tokenPrice:
                    type: string
                    label: guiziweb_sylius_token.ui.product_variant.token_price
                    path: tokenPrice
                    sortable: tokenPrice
                    position: 210
