sylius_grid:
    grids:
        guiziweb_sylius_token_shop_account_transaction:
            driver:
                name: doctrine/orm
                options:
                    class: "%guiziweb_sylius_token.model.transaction.class%"
                    repository:
                        method: createByCustomerQueryBuilder
                        arguments:
                            - "expr:service('sylius.context.customer').getCustomer()"
            sorting:
                createdAt: desc
            limits: [10, 25, 50]
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: id
                    options:
                        format: Y-m-d H:i
                type:
                    type: twig
                    label: guiziweb_sylius_token.ui.transaction.type
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/shared/grid/field/token_type.html.twig"
                amount:
                    type: twig
                    label: guiziweb_sylius_token.ui.transaction.amount
                    sortable: ~
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/shared/grid/field/token_amount.html.twig"
                context:
                    type: twig
                    label: guiziweb_sylius_token.ui.transaction.context
                    path: .
                    options:
                        template: "@GuiziwebSyliusTokenPlugin/shop/account/tokens/grid/field/context.html.twig"
