# Put your plugin configuration here

imports:
    - { resource: "resources/*.yaml" }
    - { resource: "grids/*.yaml" }
    - { resource: "fixtures.yaml" }
    - { resource: "twig_hooks/**/*.yaml" }
