sylius_twig_hooks:
    hooks:
        'sylius_admin.product.create.content.form.sections.general':
            token_amount:
                template: '@GuiziwebSyliusTokenPlugin/admin/product/form/sections/general/token_amount.html.twig'
                priority: -100
