sylius_resource:
    resources:
        guiziweb_sylius_token.wallet:
            driver: doctrine/orm
            classes:
                model: Guiziweb\SyliusTokenPlugin\Entity\TokenWallet\TokenWallet
                repository: Guiziweb\SyliusTokenPlugin\Repository\TokenWalletRepository
