sylius_twig_hooks:
    hooks:
        'guiziweb_sylius_token.admin.token_pack.update.content.header':
            breadcrumbs:
                template: '@GuiziwebSyliusTokenPlugin/admin/token_pack/update/content/header/breadcrumbs.html.twig'
                priority: 100

        'guiziweb_sylius_token.admin.token_pack.update.content.header.title_block':
            title:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
                configuration:
                    title: guiziweb_sylius_token.ui.edit_token_pack
                    icon: 'tabler:coins'
                priority: 100

        'guiziweb_sylius_token.admin.token_pack.update.content.header.title_block.actions':
            manage_variants:
                enabled: false
            show:
                template: '@GuiziwebSyliusTokenPlugin/admin/token_pack/update/content/header/title_block/actions/show.html.twig'
                priority: 400

        'guiziweb_sylius_token.admin.token_pack.update.content.form.side_navigation':
            shipping:
                enabled: false
            inventory:
                enabled: false

        'guiziweb_sylius_token.admin.token_pack.update.content.form.sections':
            shipping:
                enabled: false
            inventory:
                enabled: false

        'guiziweb_sylius_token.admin.token_pack.update.content.form.sections.general':
            shipping_required:
                enabled: false